name: pp434-canberra-pt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - geopandas
  - shapely
  - requests
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pip:
      # for GTFS realtime if you end up using it
      - gtfs-realtime-bindings
